/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Template = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'preview_image' : IDL.Text,
  'category' : IDL.Text,
  'prompt' : IDL.Text,
});

export const idlService = IDL.Service({
  'addTemplate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Template],
      [],
    ),
  'deleteTemplate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getTemplate' : IDL.Func([IDL.Nat], [IDL.Opt(Template)], ['query']),
  'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'updateTemplate' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Opt(Template)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Template = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'preview_image' : IDL.Text,
    'category' : IDL.Text,
    'prompt' : IDL.Text,
  });
  
  return IDL.Service({
    'addTemplate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Template],
        [],
      ),
    'deleteTemplate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getTemplate' : IDL.Func([IDL.Nat], [IDL.Opt(Template)], ['query']),
    'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'updateTemplate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Opt(Template)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };